alert("hello les boulets");
alert("ciao");
alert("hihi");
alert("hoho");
alert("modif sur ma branche");
alert("modif après le merge");
alert("modif sur le master");
alert("modif sur le master again");
alert("modif branche 1");
alert("modif branche 2");
alert("modif branche 3");
